---
# site.yml for expand_disk

- name: Project expand_disk
  hosts: all
  gather_facts: true
  vars:
    role_lnx_modify_disk__debug_mode: false
    role_lnx_modify_disk__secondary_disk_grow_percentage: "10%"
    role_lnx_modify_disk__root_disk_size_gb_exact_size: 60
    role_lnx_modify_disk__grow_gb_root_filesystem: 0
    role_lnx_modify_disk__grow_gb_usr_filesystem: 7
    role_lnx_modify_disk__grow_gb_var_filesystem: 10
    role_lnx_modify_disk__grow_gb_tmp_filesystem: 0
    role_lnx_modify_disk__grow_gb_home_filesystem: 0
    role_lnx_modify_disk__grow_gb_opt_filesystem: 0

  tasks:

    - name: Gather hardware facts
      ansible.builtin.setup:
        gather_subset:
          - hardware

    - name: disk_findings | Get the number of different types of controllers
      ansible.builtin.set_fact:
        __number_of_disk_controllers: >-
          {{
            ansible_facts.devices
            | dict2items
            | selectattr('value.host', 'search', 'SATA Controller|RAID Controller|NVMe Controller|PVSCSI SCSI Controller')
            | list
            | length
          }}
      changed_when: false

    - name: debug | Show the number of disk controllers
      ansible.builtin.debug:
        msg: "Number of disk controllers: {{ __number_of_disk_controllers }}"

...
