---
# tasks file for role_lnx_modify_disk - remove_secondary_vg_pvs.yml

- name: remove_secondary_vg_pvs | Move the physical volumes away from primary volume group
  ansible.builtin.command: vgreduce {{ __vg_name }} {{ item }}
  loop: "{{ __move_list }}"
  register: __vgreduce_results
  changed_when: __vgreduce_results.rc in [0,5]
#  failed_when: __vgreduce_results.rc not in [0,5]
#  ignore_errors: true

- name: remove_secondary_vg_pvs | Show debug information
  ansible.builtin.debug:
    var: __vgreduce_results
#  when: role_lnx_modify_disk__debug_mode | bool

# Sending this to ESP as configure, with role_esp_record_time__minsaved
# set to approximately time a system admin would take to perform this task
- name: remove_secondary_vg_pvs | Send record time to ESP
  ansible.builtin.include_role:
    name: centerpoint.general.role_esp_record_time
  when: role_esp_record_time__enabled | bool
  vars:
    role_esp_record_time__flag: "configure"
    role_esp_record_time__minsaved: 10

...
